# -*- coding: utf-8 -*-
"""pred_func.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nlBSoar651H7QMjdNCWhLQRy7Itud-0c
"""
import joblib

j_file = open("HACK4TKM_ML.joblib", "rb")
pred = joblib.load(j_file)

def predict(time, date, global_reactive_power, voltage) :
  h, m, s = time.split(':')
  h, m, s = int(h), int(m), int(s)
  if( h >= 12):
    apm = 1
  else :
    apm = 0

  if h > 12:
      h -= 12
  time_new = h*3600 + m*60 + s
  
  d_split = date.split("/")
  dd = int(d_split[0])
  mm = int(d_split[1])
  yyyy = int(d_split[2])

  

  return pred.predict([[time_new, 0.2, 240, apm, dd, mm, yyyy]])